### ISSUE TITLE
ArchLinux

### ISSUE THREAD

**Issue by environmentfile** [ElpersonPL/Mail-Spammer#8]
Hey, Have you heard about this distro called arch linux? It's poggers. You should switch to it.
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best
arch best

**Comment by Skilllevell** [comment]
I like android termux more
